# Generated by Django 5.2 on 2025-05-03 01:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_alter_usuario_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlaceEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del enlace, ej. Zoom principal', max_length=100)),
                ('url', models.URLField(help_text='URL del enlace')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='es_gratuito',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='evento',
            name='enlaces',
            field=models.ManyToManyField(blank=True, related_name='eventos', to='pagina.enlaceevento'),
        ),
    ]
